apiVersion: apps/v1
kind: Deployment
metadata:
  name: po-service
  labels:
    app: po-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: po-service
  template:
    metadata:
      labels:
        app: po-service
    spec:
      volumes:
      - name: mysqlcm
        configMap:
          name: mysql-db-name
      - name: mysqlse
        secret:
          secretName: mysql-secret
      containers:
      - name: po-service
        image: mtcslabtest.azurecr.io/po-service:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: mysqlcm
          mountPath: /etc/config
        - name: mysqlse
          mountPath: /etc/vol-secrets
